options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/lab-1-424317/express-api', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/lab-1-424317/express-api']

  # Step 3: Deploy the Docker image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy express-api \
          --image gcr.io/lab-1-424317/express-api \
          --platform managed \
          --region asia-southeast2 \
          --allow-unauthenticated

images:
  - 'gcr.io/lab-1-424317/express-api'
